### ISSUE TITLE
Webcam opens but it's black.

### ISSUE THREAD

**Issue by jinius17** [neuropacabra/ColorRecognizer#4]
I get the main screen but it's black and Terminal produces errors:

Color:	Black
Traceback (most recent call last):
  File "color_recognizer2.py", line 80, in redraw
    clf.fit(image, color_int)
NameError: name 'image' is not defined

**Comment by aniket414** [comment]
Even I'm getting the same problem.

Color:	Purple
  File "/Users/aniket/color_recognizer/color_recognizer2.py", line 80, in redraw
    clf.fit(image, color_int)
NameError: name 'image' is not defined

**Comment by michtesar** [comment]
What is you image resolution?*

**Comment by aniket414** [comment]
The camera starts but I can't see anything because everything is black. There's probably some error in Line 80 of color_recognizer2.py You have used image which is not defined anywhere. Just check for it.
