### ISSUE TITLE
error sklearn

### ISSUE THREAD

**Issue by agistyaanugrah** [neuropacabra/ColorRecognizer#5]
Traceback (most recent call last):
  File "D:/Kampus/Kuliah/Semester 6/Computer Vision/Project Akhir/color_recognizer-master/color_recognizer2.py", line 6, in <module>
    import vizualizator
  File "D:\Kampus\Kuliah\Semester 6\Computer Vision\Project Akhir\color_recognizer-master\vizualizator.py", line 2, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\__init__.py", line 13, in <module>
    from .validation import (as_float_array,
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\validation.py", line 22, in <module>
    from ..utils.fixes import signature
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\fixes.py", line 83, in <module>
    from scipy.special import boxcox  # noqa
  File "D:\Programming\Python\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by michtesar** [comment]
Can you provide some info what went wrong for others please?
